import {
    Book,
    Bookmark,
    LocalLibrary,
    Article,
} from '@mui/icons-material';
import SchoolIcon from '@mui/icons-material/School';
import InventoryIcon from '@mui/icons-material/Inventory';
import SubjectIcon from '@mui/icons-material/Subject';
import SupervisedUserCircleIcon from '@mui/icons-material/SupervisedUserCircle';
import DesktopMacIcon from '@mui/icons-material/DesktopMac';
import FingerprintIcon from '@mui/icons-material/Fingerprint';
import ScheduleIcon from '@mui/icons-material/Schedule';
import InfoIcon from '@mui/icons-material/Info';
import FeedbackIcon from '@mui/icons-material/Feedback';
import GavelIcon from '@mui/icons-material/Gavel';
import PhotoLibraryIcon from '@mui/icons-material/PhotoLibrary';

export const SideBarMenu = [
    {
        group: 'Dashboards',
        groupKey: 'sidebar.groups.dashboards',
        path: '/',
        icon: Book,
        label: 'Admin Dashboard',
        labelKey: 'sidebar.items.adminDashboard',
        subMenuItems: [],
        subject: 'Dashboard',
    },
    {
        group: 'Dashboards',
        groupKey: 'sidebar.groups.dashboards',
        path: '/teacher/my-dashboard',
        icon: SchoolIcon,
        label: 'My Teaching',
        labelKey: 'sidebar.items.myTeaching',
        subMenuItems: [],
        subject: 'TeacherSelfDashboard',
    },
    {
        group: 'Administration & Setup',
        groupKey: 'sidebar.groups.administration',
        path: '#',
        icon: SchoolIcon,
        label: 'Academic Setup',
        labelKey: 'sidebar.items.academicSetup',
        subMenuItems: [
            { label: 'Academic Years', labelKey: 'sidebar.items.academicYears', path: '/academic', subject: 'Academic' },
            { label: 'Term History', labelKey: 'sidebar.items.termHistory', path: '/term-history', subject: 'TermHistory' },
            { label: 'Grades', labelKey: 'sidebar.items.grades', path: '/grade', subject: 'Grade' },
            { label: 'Subjects', labelKey: 'sidebar.items.subjects', path: '/subject', subject: 'Subject' },
            { label: 'Religions', labelKey: 'sidebar.items.religions', path: '/religion', subject: 'Religion' },
            { label: 'Sections', labelKey: 'sidebar.items.sections', path: '/section', subject: 'Section' },
            { label: 'Grade Subjects', labelKey: 'sidebar.items.gradeSubjects', path: '/grade-subject', subject: 'GradeSubject' },
            { label: 'Group Subjects', labelKey: 'sidebar.items.groupSubjects', path: '/group-subject', subject: 'GroupSubject' },
            { label: 'Subject Students', labelKey: 'sidebar.items.subjectStudents', path: '/subject-student', subject: 'SubjectStudent' },
            { label: 'Exam Configuration', labelKey: 'sidebar.items.examConfiguration', path: '/exam', subject: 'Exam' },
            { label: 'Role Management', labelKey: 'sidebar.items.roleManagement', path: '/roles', subject: 'Roles' },
            { label: 'Settings', labelKey: 'sidebar.items.settings', path: '/settings', subject: 'Settings' },
        ],
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '/timetable',
        icon: ScheduleIcon,
        label: 'Timetable',
        labelKey: 'sidebar.items.timetable',
        subMenuItems: [],
        subject: 'Timetable',
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '/subject-notes',
        icon: SubjectIcon,
        label: 'Subject Notes',
        labelKey: 'sidebar.items.subjectNotes',
        subMenuItems: [],
        subject: 'SubjectNotes',
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '/lesson-plans',
        icon: Article,
        label: 'Lesson Plans',
        labelKey: 'sidebar.items.lessonPlans',
        subMenuItems: [],
        subject: 'LessonPlans',
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '/information',
        icon: InfoIcon,
        label: 'Information Desk',
        labelKey: 'sidebar.items.informationDesk',
        subMenuItems: [],
        subject: 'Information',
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '/event-gallery',
        icon: PhotoLibraryIcon,
        label: 'Event Gallery',
        labelKey: 'sidebar.items.eventGallery',
        subMenuItems: [],
        subject: 'EventGallery',
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '#',
        icon: FingerprintIcon,
        label: 'Attendance',
        labelKey: 'sidebar.items.attendance',
        subject: 'Attendance',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.attendanceOverview', path: '/attendance', subject: 'Attendance' },
            { label: 'Manual Entry', labelKey: 'sidebar.items.manualEntry', path: '/attendance/manual-attendance', subject: 'TeacherAttendance' },
            { label: 'Reports', labelKey: 'sidebar.items.attendanceReports', path: '/attendance/attendance-reports', subject: 'AttendanceReports' },
        ],
    },
    {
        group: 'Academics & Daily Operations',
        groupKey: 'sidebar.groups.academicsOperations',
        path: '#',
        icon: FeedbackIcon,
        label: 'Feedback/Discipline',
        labelKey: 'sidebar.items.feedbackDiscipline',
        subject: 'ClassFeedback',
        subMenuItems: [
            { label: 'Class Feedback', labelKey: 'sidebar.items.classFeedback', path: '/feedback/class', subject: 'ClassFeedback' },
            { label: 'Subject Feedback', labelKey: 'sidebar.items.subjectFeedback', path: '/feedback/subject', subject: 'SubjectFeedback' },
        ],
    },
    {
        group: 'Operations',
        groupKey: 'sidebar.groups.operations',
        path: '#',
        icon: InventoryIcon,
        label: 'Inventory',
        labelKey: 'sidebar.items.inventory',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.inventoryOverview', path: '/inventory', subject: 'Inventory' },
            { label: 'Products', labelKey: 'sidebar.items.inventoryProducts', path: '/inventory/products', subject: 'InventoryProducts' },
            { label: 'Purchase', labelKey: 'sidebar.items.inventoryPurchase', path: '/inventory/purchase', subject: 'InventoryPurchase' },
            { label: 'Categories', labelKey: 'sidebar.items.inventoryCategories', path: '/inventory/category', subject: 'InventoryCategory' },
            { label: 'Sub Categories', labelKey: 'sidebar.items.inventorySubCategories', path: '/inventory/sub-category', subject: 'InventorySubCategory' },
            { label: 'Units', labelKey: 'sidebar.items.inventoryUnits', path: '/inventory/units', subject: 'InventoryUnit' },
            { label: 'Stores', labelKey: 'sidebar.items.inventoryStores', path: '/inventory/store', subject: 'InventoryStore' },
            { label: 'Sales', labelKey: 'sidebar.items.inventorySales', path: '/inventory/sales', subject: 'InventorySales' },
            { label: 'Reports', labelKey: 'sidebar.items.inventoryReports', path: '/inventory/report', subject: 'InventoryReport' },
        ],
    },
    {
        group: 'People & Access',
        groupKey: 'sidebar.groups.peopleAccess',
        path: '#',
        icon: SupervisedUserCircleIcon,
        label: 'People & Access',
        labelKey: 'sidebar.items.peopleAccess',
        subMenuItems: [
            { label: 'Teacher Dashboard', labelKey: 'sidebar.items.teacherDashboard', path: '/teacher', subject: 'TeacherDashboard' },
            { label: 'Teacher Management', labelKey: 'sidebar.items.teacherManagement', path: '/teacher/list', subject: 'Teacher' },
            { label: 'Student Dashboard', labelKey: 'sidebar.items.studentDashboard', path: '/student', subject: 'StudentDashboard' },
            { label: 'Student Management', labelKey: 'sidebar.items.studentManagement', path: '/student/list', subject: 'Student' },
        ],
    },
    {
        group: 'Assessments',
        groupKey: 'sidebar.groups.assessments',
        path: '#',
        icon: DesktopMacIcon,
        label: 'Online Exams',
        labelKey: 'sidebar.items.onlineExams',
        subject: 'Exams',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.onlineExamOverview', path: '/online-exam', subject: 'Exams' },
            { label: 'Question Bank', labelKey: 'sidebar.items.questionBank', path: '/online-exam/question-bank', subject: 'QuestionBank' },
            { label: 'Exam List', labelKey: 'sidebar.items.examList', path: '/online-exam/list', subject: 'Exams' },
        ],
    },
    {
        group: 'Assessments',
        groupKey: 'sidebar.groups.assessments',
        path: '#',
        icon: Book,
        label: 'Assignments',
        labelKey: 'sidebar.items.assignments',
        subject: 'Assignments',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.assignmentsOverview', path: '/assignments', subject: 'Assignments' },
            { label: 'Manage Assignments', labelKey: 'sidebar.items.manageAssignments', path: '/assignments/list', subject: 'Assignments' },
        ],
    },
    {
        group: 'Assessments',
        groupKey: 'sidebar.groups.assessments',
        path: '/exammark',
        icon: Bookmark,
        label: 'Exam Marks',
        labelKey: 'sidebar.items.examMarks',
        subject: 'ExamMark',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.examMarkOverview', path: '/exammark', subject: 'ExamMarkDashboard' },
        ],
    },
    {
        group: 'Resources & Communication',
        groupKey: 'sidebar.groups.resourcesCommunication',
        path: '#',
        icon: LocalLibrary,
        label: 'Library',
        labelKey: 'sidebar.items.library',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.libraryOverview', path: '/library', subject: 'Library' },
            { label: 'Categories', labelKey: 'sidebar.items.libraryCategories', path: '/library/categories', subject: 'LibraryCategories' },
            { label: 'Book Catalogs', labelKey: 'sidebar.items.bookCatalogs', path: '/library/catalogs', subject: 'LibraryBookCatalog' },
            { label: 'Racks', labelKey: 'sidebar.items.racks', path: '/library/racks', subject: 'LibraryRacks' },
            { label: 'Books', labelKey: 'sidebar.items.books', path: '/library/books', subject: 'LibraryBooks' },
            { label: 'Issue / Return', labelKey: 'sidebar.items.issueReturn', path: '/library/issues', subject: 'LibraryBookIssue' },
            { label: 'My Books', labelKey: 'sidebar.items.myBooks', path: '/library/teachers-books', subject: 'LibraryMyBooks' },
        ],
    },
    {
        group: 'Resources & Communication',
        groupKey: 'sidebar.groups.resourcesCommunication',
        path: '#',
        icon: Article,
        label: 'Blog',
        labelKey: 'sidebar.items.blog',
        subMenuItems: [
            { label: 'Overview', labelKey: 'sidebar.items.blogOverview', path: '/blog', subject: 'Blog' },
            { label: 'Manage Posts', labelKey: 'sidebar.items.managePosts', path: '/blog/posts', subject: 'BlogPosts' },
            { label: 'Manage Comments', labelKey: 'sidebar.items.manageComments', path: '/blog/comments', subject: 'BlogComments' },
            { label: 'View Blog', labelKey: 'sidebar.items.viewBlog', path: '/blog/view', subject: 'BlogView' },
        ],
    },
];

export const StudentMenus = [
    {
        group: 'Overview',
        groupKey: 'studentSidebar.groups.overview',
        path: '/students',
        icon: Book,
        label: 'Dashboard',
        labelKey: 'studentSidebar.items.dashboard',
        subMenuItems: [],
    },
    {
        group: 'Overview',
        groupKey: 'studentSidebar.groups.overview',
        path: '/students/timetable',
        icon: ScheduleIcon,
        label: 'My Timetable',
        labelKey: 'studentSidebar.items.myTimetable',
        subMenuItems: [],
    },
    {
        group: 'Academics',
        groupKey: 'studentSidebar.groups.academics',
        path: '/students/subject-notes',
        icon: SubjectIcon,
        label: 'Subject Notes',
        labelKey: 'studentSidebar.items.subjectNotes',
        subMenuItems: [],
    },
    {
        group: 'Academics',
        groupKey: 'studentSidebar.groups.academics',
        path: '/students/lesson-plans',
        icon: Article,
        label: 'Lesson Plans',
        labelKey: 'studentSidebar.items.lessonPlans',
        subMenuItems: [],
    },
    {
        group: 'Academics',
        groupKey: 'studentSidebar.groups.academics',
        path: '/students/attendance',
        icon: FingerprintIcon,
        label: 'My Attendance',
        labelKey: 'studentSidebar.items.myAttendance',
        subMenuItems: [],
    },
    {
        group: 'Academics',
        groupKey: 'studentSidebar.groups.academics',
        path: '/students/feedback',
        icon: FeedbackIcon,
        label: 'Feedback',
        labelKey: 'studentSidebar.items.feedback',
        subMenuItems: [],
    },
    {
        group: 'Academics',
        groupKey: 'studentSidebar.groups.academics',
        path: '/students/discipline',
        icon: GavelIcon,
        label: 'Discipline',
        labelKey: 'studentSidebar.items.discipline',
        subMenuItems: [],
    },
    {
        group: 'Resources',
        groupKey: 'studentSidebar.groups.resources',
        path: '#',
        icon: InfoIcon,
        label: 'Information',
        labelKey: 'studentSidebar.items.information',
        subMenuItems: [
            { label: 'All Information', labelKey: 'studentSidebar.items.allInformation', path: '/students/information', subject: 'Information' },
            { label: 'Information Desk', labelKey: 'studentSidebar.items.informationDesk', path: '/students/information/information-desk', subject: 'Information' },
            { label: 'Help Desk', labelKey: 'studentSidebar.items.helpDesk', path: '/students/information/help-desk', subject: 'Information' },
            { label: 'General Information', labelKey: 'studentSidebar.items.generalInformation', path: '/students/information/general-information', subject: 'Information' },
        ],
    },
    {
        group: 'Assessments',
        groupKey: 'studentSidebar.groups.assessments',
        path: '/students/online-exam',
        icon: DesktopMacIcon,
        label: 'Online Exams',
        labelKey: 'studentSidebar.items.onlineExams',
        subMenuItems: [],
    },
    {
        group: 'Assessments',
        groupKey: 'studentSidebar.groups.assessments',
        path: '/students/online-assignment',
        icon: Book,
        label: 'Assignments',
        labelKey: 'studentSidebar.items.assignments',
        subMenuItems: [],
    },
    {
        group: 'Assessments',
        groupKey: 'studentSidebar.groups.assessments',
        path: '/students/exammark',
        icon: Bookmark,
        label: 'Exam Marks',
        labelKey: 'studentSidebar.items.examMarks',
        subMenuItems: [],
    },
    {
        group: 'Community & Resources',
        groupKey: 'studentSidebar.groups.communityResources',
        path: '/students/blog',
        icon: Article,
        label: 'School Blog',
        labelKey: 'studentSidebar.items.schoolBlog',
        subMenuItems: [],
    },
    {
        group: 'Community & Resources',
        groupKey: 'studentSidebar.groups.communityResources',
        path: '/students/event-gallery',
        icon: PhotoLibraryIcon,
        label: 'Event Gallery',
        labelKey: 'studentSidebar.items.eventGallery',
        subMenuItems: [],
    },
    {
        group: 'Community & Resources',
        groupKey: 'studentSidebar.groups.communityResources',
        path: '/students/library',
        icon: LocalLibrary,
        label: 'My Library',
        labelKey: 'studentSidebar.items.myLibrary',
        subMenuItems: [],
    },
];
